target:
  image: ansible_target:latest
  container_name: ansible_target
  expose:
    - "22"
  volumes:
    - ~/.ssh/id_rsa.pub:/home/ec2-user/.ssh/authorized_keys
  privileged: true

test:
  image: vg-playbook:latest
  links:
    - target
  volumes:
    - ~/.ssh/id_rsa:/root/.ssh/id_rsa
    - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
    - .:/ansible/playbooks
